#!/bin/bash

sudo apt-get install git software-properties-common python3 python3-tk python3-software-properties

sudo add-apt-repository ppa:alessandro-strada/ppa
sudo apt-get update
sudo apt-get install google-drive-ocamlfuse

cd ~/
git clone https://github.com/jernesten/ogui

source $HOME/.config/user-dirs.dirs
touch  $HOME/ogui/ogui.desktop
echo -e "[Desktop Entry]\nType=Application\nIcon="$HOME"/.local/share/ogui/images/ogui.png\nName=ogui\nGenericName=ogui\nComment=GUI for gdrive ocamlfuse\nCategories=Internet;\nExec="$HOME"/.local/share/ogui/py/ogui\nTerminal=false" >> $HOME/ogui/ogui.desktop
$HOME/ogui/ogui.desktop

cp -R ~/ogui ~/.local/share
cp ~/ogui/ogui.desktop ~/.local/share/applications/ogui.desktop

exit
