#!/bin/bash

sudo apt-get install git software-properties-common python3 python3-tk python3-software-properties

sudo add-apt-repository ppa:alessandro-strada/ppa
sudo apt-get update
sudo apt-get install google-drive-ocamlfuse

cd ~/
git clone https://github.com/jernesten/ogui
rm -R -f ~/ogui/.git

touch  ~/ogui/ogui.desktop
echo "[Desktop Entry]\nType=Application\nIcon="$HOME"/.local/share/ogui/images/ogui.png\nName=ogui\nGenericName=ogui\nComment=GUI for gdrive ocamlfuse\nCategories=Network;\nExec="$HOME"/.local/share/ogui/py/ogui\nPath="$HOME"/.local/share/ogui\nTerminal=false" >> $HOME/ogui/ogui.desktop
chmod +x ~/ogui/ogui.desktop

chmod +x ~/ogui/py/ogui

cp -R ~/ogui ~/.local/share
cp ~/ogui/ogui.desktop ~/.local/share/applications/ogui.desktop

exit
